# Generated by Django 4.2.5 on 2023-10-07 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_contactmessage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactMessage',
        ),
    ]
